export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
export const SET_CATEGORIES= 'SET_CATEGORIES';
export const SET_PRODUCT_LIST= 'SET_PRODUCT_LIST';
export const SET_TOTAL= 'SET_TOTAL';
export const SET_FETCH_STATE= 'SET_FETCH_STATE';
export const SET_LIMIT= 'SET_LIMIT';
export const SET_OFFSET= 'SET_OFFSET';
export const SET_FILTER= 'SET_FILTER';
export const FETCH_PRODUCTS_URL= 'FETCH_PRODUCTS_URL';
export const FETCH_PRODUCT_REQUEST="FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS="FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL="FETCH_PRODUCT_FAIL";
export const ADD_TO_CART=" ADD_TO_CART ";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const UPDATE_CART_ITEM="UPDATE_CART_ITEM";
export const LOGOUT_USER="LOGOUT_USER";
export const UPDATE_CART_ITEM_QUANTITY ="UPDATE_CART_ITEM_QUANTITY";
export const TOGGLE_FAVORITE="TOGGLE_FAVORITE";

export const SET_ADDRESSES = "SET_ADDRESSES";
export const ADD_ADDRESS="ADD_ADDRESS";
export const UPDATE_ADDRESS="UPDATE_ADDRESS";
export const DELETE_ADDRESS="DELETE_ADDRESS";
 