export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
export const SET_CATEGORIES= 'SET_CATEGORIES';
export const SET_PRODUCT_LIST= 'SET_PRODUCT_LIST';
export const SET_TOTAL= 'SET_TOTAL';
export const SET_FETCH_STATE= 'SET_FETCH_STATE';
export const SET_LIMIT= 'SET_LIMIT';
export const SET_OFFSET= 'SET_OFFSET';
export const SET_FILTER= 'SET_FILTER';
export const FETCH_PRODUCTS_URL= 'FETCH_PRODUCTS_URL';



 